config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#biography'
  # get 'biography'    => 'static_pages#biography',    as: 'biography'
  get 'portfolio'   => 'static_pages#portfolio',  as: 'portfolio'
  get 'skillset'    => 'static_pages#skillset',   as: 'skillset'
  # get 'contact'     => 'static_pages#contact',    as: 'contact'

  # match '/contact',     to: 'contacts#new',             via: 'get'
  # resources "contacts", only: [:new, :create]

  get 'contact'   => 'contacts#new', as: 'contact'
  post 'contact'  => 'contacts#create', as: 'contacts'

end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :telephone
  attribute :message,   :validate => true
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Contact paulld.com",
      :to => "paul.lugagnedelpon@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/contact_form.rb
class ContactForm < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :file,      :attachment => true

  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "My Contact Form",
      :to => "paul.lugagnedelpon@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/message.rb
class Message < ActiveRecord::Base

  # validates :name, presence: true
  # validates :email, presence: true, format: { with: /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i,
  #                                             message: "Please input correct email address" }
  # validates :message, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request

    if @contact.deliver
      Message.create(contact_params)
      flash.now[:notice] = 'Thank you for your message! I will get back to you as soon as possible'
    else
      flash.now[:error] = 'You message could not be sent. Please try again.'
      render :new
    end
  end

private
  def contact_params
    params.require(:contact).permit(:name, :email, :telephone, :message)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def biography
  end

  def portfolio
  end

  def skillset
  end

  def contact
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def is_active?(link_path)
    current_page?(link_path) ? "active" : ""
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/contacts/create.html.erb
<section id="contact-success" class="main-width-small main-height-medium">
  <header>
    <h1 class="sr-only">Contact</h1>
  </header>

  <div>
    <% flash.each do |key, value| %>
      <p class="lead contact-text">
        <%= value %>
      </p>
    <% end %>
  </div>

  <!-- <p class="lead contact-text">
    You may also visit my&nbsp;
    <a class="portfolio-link" href="https://github.com/paulld" name="View my Github account">GitHub</a>
    &nbsp;and&nbsp;
    <a class="portfolio-link" href="https://www.linkedin.com/in/paullugagnedelpon" name="View my Linkedin profile">LinkeIn</a>
    &nbsp;accounts
  </p> -->
</section>

app/views/contacts/new.html.erb
<section id="skillset" class="main-width-small main-height-large">
  <header>
    <!-- <h1 class="cover-heading">I would love to hear from you!</h1 -->
    <h1 class="cover-heading">Get in Touch</h1>
  </header>
  <p class="lead contact-text">
  Do you have an interesting project or just want to say hi?<br>Send me a message!
    <!-- Please leave me a message<br>and I will get back to you shortly: -->
  </p>

  <div>
    <% flash.each do |key, value| %>
      <p class="lead contact-text">
        <%= value %>
      </p>
    <% end %>
  </div>

  <div align="center">
    <%= simple_form_for @contact, :html => {:class => 'form-horizontal contact-form' } do |f| %>
      <div class="form-group">
        <%= f.input :name, :required => true, input_html: { class: 'form-control' }, label: false, placeholder: 'Your Name / Company' %>
        <%= f.input :email, :required => true, input_html: { class: 'form-control' }, label: false, placeholder: 'Your Email Address' %>
        <%= f.input :telephone, :required => false, input_html: { class: 'form-control' }, label: false, placeholder: 'Your Telephone number' %>
      </div>
      <div class="form-group">
        <%= f.input :message, :as => :text, :required => true, input_html: { class: 'form-control' }, label: false, placeholder: 'How can I help you?' %>
      </div>
      <div class= "hidden">
        <%= f.input :nickname, :hint => 'Leave this field blank!' %>
      </div>
      <div class="form-group">
        <%= f.button :submit, 'Send message', :class=> "btn btn-lg btn-default btn-contact" %>
      </div>
    <% end %>
  </div>
  <!-- <p class="lead contact-text contact-links">
    Alternatively, I am reachable via Skype:
    <a class="portfolio-link" href="skype:paul.ld?add" name="Add me on Skype">paul.ld</a>
    <br>or by email:
    <a class="portfolio-link" href="mailto:paul@pld.me" name="Send me an email">paul@pld.me</a>
  </p> -->
</section>

app/views/layouts/_footer.html.erb
<section>
  <header>
    <h1 class="sr-only">Personal accounts</h1>
  </header>
  <ul class="list-inline social-media">
    <li>
      <a href="https://github.com/paulld" name="View my Github account">
      <i class="fa fa-github-square"></i></a>
    </li>
    <li>
      <a href="https://www.linkedin.com/in/paullugagnedelpon" name="View my Linkedin profile">
      <i class="fa fa-linkedin-square"></i></a>
    </li>
    <li>
      <a href="https://twitter.com/paul__ld" name="Access my Twitter account">
      <i class="fa fa-twitter"></i></a>
    </li>
    <li>
      <a href="skype:paul.ld?add" name="Add me on Skype">
      <i class="fa fa-skype"></i></a>
    </li>
    <li>
      <a href="mailto:paul@pld.me" name="Send me an email">
      <i class="fa fa-envelope-o"></i></a>
    </li>
  </ul>
</section>

app/views/layouts/_header.html.erb
<div class="head-small">
  <div class="inner" role="navigation">
    <div class="pld-logo">
      <h1 class="sr-only">paul ld | web development</h1>
      <%= image_tag 'paulld-logo-webdev.svg' %>
    </div>
    <ul id="header-navlinks" class="nav masthead-nav" role="menubar">
      <li role="presentation" class="<%= is_active?(root_path)%>"><%= link_to "Biography", root_path %></li>
      <!-- <li role="presentation" class="<%= is_active?(portfolio_path)%>"><#%= link_to "Portfolio", portfolio_path %></li>
      <li role="presentation" class="<%= is_active?(skillset_path)%>"><#%= link_to "Skillset", skillset_path %></li> -->
      <li role="presentation" class="<%= is_active?(contact_path)%>"><%= link_to "Contact", contact_path %></li>
      <!-- <li role="presentation" class="<%= is_active?(contact_path)%> <#% if "contacts".include?(params[:controller])%><#%= "active" %><#% end %>"><#%= link_to "Contact", contact_path %></li> -->
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>paul ld | web development</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicon.ico' %>
  
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="//oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="//oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <header id="header" role="banner">
      <%= render partial: "layouts/header" %>
    </header>

    <main id="main" class="inner cover" role="main">
      <%= yield %>
      <div class="push"></div>
    </main>

    <footer id="footer" role="footer">
      <%= render partial: "layouts/footer" %>
    </footer>

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
      ga('create', 'UA-52793806-1', 'auto');
      ga('send', 'pageview');
    </script>
  </body>
</html>

app/views/static_pages/biography.html.erb
<section id="biography" class="main-width-small main-height-large">
  <header>
    <h1 class="cover-heading">About me</h1>
  </header>
  <%= image_tag "paulld-profile-picture.jpg", :class => "profile-picture" %>
  <!-- <p class="lead lead-biography">Thank you for visiting my site!</p> -->
  <p class="lead lead-biography">
    I am a former investment banker turned passionate web developer.<br>
    I made the move to do things I love!
  </p>
  <p class="lead lead-biography">
    I not only do my best to build great applications, but also enjoy brainstorming,
    planning, and implementing business ideas. I work hard to build web applications
    that are accessible, usable, functional, and beautiful.
  </p>
  <p class="lead lead-biography">
    Two of my favorite activities, coding and sports, have the same keys 
    to success - fun and practice
  </p>
  <!-- <p class="lead lead-biography">
    I enjoy learning new frameworks and languages, with a current preference for 
    Ruby on Rails, Node.js, AngularJS, and Meteor. I use the PostgreSQL and MongoDB 
    databases extensively, and I spend significant time improving my skills in 
    usability, accessibility (to people with disabilities), and Agile web development.
  </p> -->
</section>

app/views/static_pages/contact.html.erb
<section id="contact" class="main-width-small main-height-medium">
  <header>
    <h1 class="cover-heading">Contact Me</h1>
  </header>
  <p class="lead contact-text">
    I would love to hear from you!
  </p>
  <p class="lead contact-text">
    <br>Please contact me by email:&nbsp;
    <a class="portfolio-link" href="mailto:paul@pld.me" name="Send me an email">paul@pld.me</a>
    &nbsp;or via Skype:&nbsp;
    <a class="portfolio-link" href="skype:paul.ld?add" name="Add me on Skype">
      paul.ld
    </a>
  </p>
  <p class="lead contact-text">
    <br>Alternatively, you may visit my&nbsp;
    <a class="portfolio-link" href="https://github.com/paulld" name="View my Github account">GitHub</a>
    &nbsp;and&nbsp;
    <a class="portfolio-link" href="https://www.linkedin.com/in/paullugagnedelpon" name="View my Linkedin profile">LinkeIn</a>
    &nbsp;accounts
  </p>
  <p class="lead contact-text">
    <br>I also&nbsp;
    <a class="portfolio-link" href="https://twitter.com/paul__ld" name="View my Twitter page">Tweet</a>
    &nbsp;in English and French
  </p>
</section>

app/views/static_pages/portfolio.html.erb
<section id="portfolio" class="main-width-x-medium main-height-large">
  <header>
    <h1 class="cover-heading">Selected work</h1>
  </header>
  <div class="container">

    <div class="row">
      <div class="col-lg-6 col-md-6 text-center">
        <a href="http://arimor-consulting.de/">
          <%= image_tag "paulld-portfolio-arimorc.jpg", :class => "img-responsive", :alt => "Arimor Consulting - screenshot" %>
        </a>
      </div>
      <div class="col-lg-6 col-md-5">
        <h2>Arimor Consulting</h2>
        <p class="portfolio-description">
          New company website, custom design, multi-language, dedicated CMS.
        </p>
        <p class="portfolio-tools">
          <u>Frameworks &amp; Database</u>: 
          <a class="portfolio-link" href="http://nodejs.org/">Node.JS</a>, 
          <a class="portfolio-link" href="https://angularjs.org/">AngularJS</a>,
          <a class="portfolio-link" href="http://www.mongodb.org/">MongoDB</a>.
        </p>
        <p class="portfolio-tools">
          <u>Languages</u>: 
          <a class="portfolio-link" href="https://developer.mozilla.org/en-US/docs/Web/javascript"><a class="portfolio-link" href="https://developer.mozilla.org/en-US/docs/Web/javascript">JavaScript</a></a>, 
          <a class="portfolio-link" href="http://www.w3.org/TR/html5/">HTML5</a>, 
          <a class ="portfolio-link" href="http://sass-lang.com/">SCSS</a>, 
          Responsive Design.
        </p>
        <a class="btn btn-md btn-default" href="http://arimor-consulting.de/">
          View Project <span class="glyphicon glyphicon-chevron-right"></span>
        </a>
      </div>
    </div>
    <hr>

    <div class="row">
      <div class="col-lg-6 col-md-6 text-center">
        <!-- <a href="http://blog.digit.co/"> -->
          <%= image_tag "paulld-portfolio-keneo.jpg", :class => "img-responsive", :alt => "Keneo - screenshot" %>
        <!-- </a> -->
      </div>
      <div class="col-lg-6 col-md-5">
        <h2>Keneo Sport Solutions</h2>
        <p class="portfolio-description">
          Redesigned the internal reporting website.
        </p>
        <p class="portfolio-tools">
          <u>Languages &amp; Libraries</u>: 
          <a class="portfolio-link" href="https://developer.mozilla.org/en-US/docs/Web/javascript"><a class="portfolio-link" href="https://developer.mozilla.org/en-US/docs/Web/javascript">JavaScript</a></a>, 
          <a class="portfolio-link" href="http://jquery.com/">jQuery</a>, 
          <a class="portfolio-link" href="http://www.w3.org/TR/html5/">HTML5</a>, 
          <a class ="portfolio-link" href="http://www.w3.org/Style/CSS/">CSS3</a>, 
          Responsive Design.
        </p>
      </div>
    </div>
    <hr>

    <div class="row">
      <div class="col-lg-6 col-md-6 text-center">
        <a href="http://blog.digit.co/">
          <%= image_tag "paulld-portfolio-digit.jpg", :class => "img-responsive", :alt => "Glimmer - screenshot" %>
        </a>
      </div>
      <div class="col-lg-6 col-md-5">
        <h2>Digit Blog</h2>
        <p class="portfolio-description">
          Development of a custom Tumblr Theme for the Digit Blog.
        </p>
        <p class="portfolio-tools">
          <u>Languages &amp; Libraries</u>: 
          <a class="portfolio-link" href="https://www.tumblr.com/docs/en/custom_themes">Tumblr Custom Theme</a>, <a class="portfolio-link" href="https://developer.mozilla.org/en-US/docs/Web/javascript"><a class="portfolio-link" href="https://developer.mozilla.org/en-US/docs/Web/javascript">JavaScript</a></a>, 
          <a class="portfolio-link" href="http://www.w3.org/TR/html5/">HTML5</a>, 
          <a class ="portfolio-link" href="http://www.w3.org/Style/CSS/">CSS3</a>.
        </p>
        <p class="portfolio-tools">
          <u>Design Tools</u>: 
          <a class="portfolio-link" href="http://bohemiancoding.com/sketch/">Sketch</a>, 
          <a class="portfolio-link" href="http://www.invisionapp.com/">Invision</a>.
        </p>
        <a class="btn btn-md btn-default" href="http://blog.digit.co/">
          View Project <span class="glyphicon glyphicon-chevron-right"></span>
        </a>
      </div>
    </div>
    <hr>

    <div class="row">
      <div class="col-lg-6 col-md-6 text-center">
        <a href="">
        </a>
      </div>
      <div class="col-lg-6 col-md-5">
        <h2>Altitude Labs</h2>
        <p class="portfolio-description">
          Development of an internal software for a design agency.
          <br>
          Sorting algorithm and extensive use of Scalable Vector Graphics.
        </p>
        <p class="portfolio-tools">
          <u>Frameworks &amp; Database</u>: 
          <a class="portfolio-link" href="http://nodejs.org/">Node.JS</a>, 
          <a class="portfolio-link" href="https://angularjs.org/">AngularJS</a>,
          <a class="portfolio-link" href="http://www.mongodb.org/">MongoDB</a>.
        </p>
        <p class="portfolio-tools">
          <u>Languages &amp; Tools</u>: 
          <a class="portfolio-link" href="https://developer.mozilla.org/en-US/docs/Web/javascript"><a class="portfolio-link" href="https://developer.mozilla.org/en-US/docs/Web/javascript">JavaScript</a></a>, 
          <a class="portfolio-link" href="http://www.w3.org/TR/html5/">HTML5</a>, 
          <a class ="portfolio-link" href="http://www.w3.org/Style/CSS/">CSS3</a>, 
          <a class="portfolio-link" href="http://www.w3.org/TR/SVG/">SVG</a>.
        </p>
      </div>
    </div>
    <hr>

    <div class="row">
      <div class="col-lg-6 col-md-6 text-center">
        <a href="http://paul.lugagnedelpon.com/glimmer/">
          <%= image_tag "paulld-portfolio-glimmer.jpg", :class => "img-responsive", :alt => "Glimmer - screenshot" %>
        </a>
      </div>
      <div class="col-lg-6 col-md-5">
        <h2>Glimmer</h2>
        <p class="portfolio-description">
          Glimmer is an eye-tracking app that allows fully immobile patients (due to ALS, SMA, stroke, spinal injury etc.) to communicate via eye movement. Glimmer works with any browser and camera.
        </p>
        <p class="portfolio-description">
          Winner of the 2014 Hacking Health hackathon in Hong Kong.
        </p>
        <p class="portfolio-tools">
          <u>Languages &amp; Libraries</u>: 
          <a class="portfolio-link" href="https://developer.mozilla.org/en-US/docs/Web/javascript"><a class="portfolio-link" href="https://developer.mozilla.org/en-US/docs/Web/javascript">JavaScript</a></a>, 
          <a class="portfolio-link" href="https://github.com/wallarelvo/camgaze.js">Camgaze.js</a>, 
          <a class="portfolio-link" href="http://www.w3.org/TR/html5/">HTML</a>, 
          <a class ="portfolio-link" href="http://www.w3.org/Style/CSS/">CSS</a>.
        </p>
        <a class="btn btn-md btn-default" href="http://paul.lugagnedelpon.com/glimmer/">
          View Project <span class="glyphicon glyphicon-chevron-right"></span>
        </a>
      </div>
    </div>
    <hr>

    <div class="row">
      <div class="col-lg-6 col-md-6 text-center">
        <a href="https://github.com/paulld/prediktapp">
          <%= image_tag "paulld-portfolio-predikt.jpg", :class => "img-responsive", :alt => "Predikt - screenshot" %>
        </a>
      </div>
      <div class="col-lg-6 col-md-5">
        <h2>Predikt</h2>
        <p class="portfolio-description">
          Predikt is a sports bet simulation app. Users can use in-game currency to practice their 
          gambling skills, test strategies, interact with other users, and share betting tips.
        </p>
        <p class="portfolio-tools">
          <u>Frameworks, Database &amp; Others</u>: 
          <a class="portfolio-link" href="http://rubyonrails.org/">Ruby on Rails</a>, 
          <a class="portfolio-link" href="https://angularjs.org/">AngularJS</a>, 
          <a class="portfolio-link" href="http://www.postgresql.org/">PostgreSQL</a>, 
          built-in JSON API following the 
          <a class="portfolio-link" href="http://jsonapi.org/">json:api</a> 
          standard, built-in authentification process.
        </p>
        <p class="portfolio-tools">
          <u>Languages</u>: 
          <a class="portfolio-link" href="https://www.ruby-lang.org/en/">Ruby</a>, 
          <a class="portfolio-link" href="http://coffeescript.org/">CoffeeScript</a>, 
          <a class="portfolio-link" href="http://www.w3.org/TR/html5/">HTML5</a> / 
          <a class="portfolio-link" href="http://slim-lang.com/">Slim</a>, 
          <a class ="portfolio-link" href="http://www.w3.org/Style/CSS/">CSS3</a> / 
          <a class="portfolio-link" href="http://learnboost.github.io/stylus/">Stylus</a>, 
          Responsive Design.
        </p>
        <a class="btn btn-md btn-default" href="https://github.com/paulld/prediktapp">
          View Repo <span class="glyphicon glyphicon-chevron-right"></span>
        </a>
      </div>
    </div>
    <hr>

    <div class="row">
      <div class="col-lg-6 col-md-6">
        <a href="http://artypedia.herokuapp.com/">
          <%= image_tag "paulld-portfolio-artypedia.jpg", :class => "img-responsive", :alt => "ArtyPedia - screenshot" %>
        </a>
      </div>
      <div class="col-lg-6 col-md-5">
        <h2>ArtyPedia</h2>
        <p class="portfolio-description">
          Artypedia is a Wiki-like Art library project. It aims at gathering in one place 
          all major artists, and referencing them to their complete list of artworks. 
          It currently concentrates on modern art.
        </p>
        <p class="portfolio-tools">
          <u>Framework</u>: 
          <a class="portfolio-link" href="http://emberjs.com/">Ember.js</a>, 
          using the 
          <a class="portfolio-link" href="https://github.com/stefanpenner/ember-cli">Ember-CLI</a> 
          executable.
        </p>
        <p class="portfolio-tools">
          <u>Languagues</u>: 
          <a class="portfolio-link" href="http://coffeescript.org/">CoffeeScript</a>, 
          <a class="portfolio-link" href="http://emberscript.com/">EmberScript</a>, 
          <a class="portfolio-link" href="http://emblemjs.com/">Emblem</a>, 
          <a class="portfolio-link" href="http://learnboost.github.io/stylus/">Stylus</a>.
        </p>
        <a class="btn btn-md btn-default" href="http://artypedia.herokuapp.com/">
          View Project <span class="glyphicon glyphicon-chevron-right"></span>
        </a>
        <a class="btn btn-md btn-default" href="https://github.com/paulld/artypedia-embercli">
          View Repo <span class="glyphicon glyphicon-chevron-right"></span>
        </a>
      </div>
    </div>
    <hr>

    <div class="row">
      <div class="col-lg-6 col-md-6">
        <a href="https://github.com/paulld/chattr">
          <%= image_tag "paulld-portfolio-chattr.jpg", :class => "img-responsive", :alt => "Chattr - screenshot" %>
        </a>
     </div>
      <div class="col-lg-6 col-md-5">
        <h2>Chattr</h2>
        <p class="portfolio-description">
          Chattr is Chat application running on Meteor, part of an open-source 
          course management system. It allows creating archivable vs. temporary chatrooms, 
          sharing links, code snippets, and files. Requires GitHub authentification.
        </p>
        <p class="portfolio-tools">
          <u>Framework &amp; Database</u>: 
          <a class="portfolio-link" href="https://www.meteor.com/">Meteor.js</a>, 
          <a class="portfolio-link" href="http://www.mongodb.org/">MongoDB</a>.
        </p>
        <p class="portfolio-tools">
          <u>Languages</u>: 
          <a class="portfolio-link" href="http://coffeescript.org/">CoffeeScript</a>, 
          <a class="portfolio-link" href="http://www.w3.org/TR/html5/">HTML5</a>, 
          <a class="portfolio-link" href="http://learnboost.github.io/stylus/">Stylus</a> / 
          <a class ="portfolio-link" href="http://www.w3.org/Style/CSS/">CSS3</a>, 
          <a class ="portfolio-link" href="http://lesscss.org/">Less</a>, 
          Responsive Design.
        </p>
        <a class="btn btn-md btn-default" href="https://github.com/paulld/chattr">
          View Repo <span class="glyphicon glyphicon-chevron-right"></span>
        </a>
      </div>
    </div>
    <hr>

    <div class="row">
      <div class="col-lg-6 col-md-6">
        <a href="http://clemencetorres.com/">
          <%= image_tag "paulld-portfolio-clemencetorres.jpg", :class => "img-responsive", :alt => "ClemenceTorres - screenshot" %>
        </a>
      </div>
      <div class="col-lg-6 col-md-5">
        <h2>ClemenceTorres</h2>
        <p class="portfolio-description">
          Portfolio website for French artist Clémence Torres.
        </p>
        <p class="portfolio-tools">
          <u>Languages</u>: 
          <a class="portfolio-link" href="http://www.w3.org/TR/html5/">HTML</a>, 
          <a class ="portfolio-link" href="http://www.w3.org/Style/CSS/">CSS</a>, 
          <a class="portfolio-link" href="https://developer.mozilla.org/en-US/docs/Web/javascript">JavaScript</a>.
        </p>
        <a class="btn btn-md btn-default" href="http://clemencetorres.com/">
          View Project <span class="glyphicon glyphicon-chevron-right"></span>
        </a>
      </div>
    </div>
  </div>
</section>

app/views/static_pages/skillset.html.erb
<section id="skillset" class="main-width-medium main-height-large">
  <header>
    <h1 class="cover-heading">Technical Skillset</h1>
  </header>
  <div class="skills-list">
    <dl class="dl-horizontal">
      <dt>Programming languages &amp; libraries</dt>
      <dd>JavaScript, CoffeeScript, Ruby, EmberScript, jQuery</dd>

      <dt>Frameworks</dt>
      <dd>Ruby on Rails, Node.js, AngularJS, Ionic, Meteor</dd>

      <!-- <dt>Libraries</dt> -->
      <!-- <dd>jQuery, </dd> -->

      <dt>Markup languages</dt>
      <dd>HTML5, Slim, Emblem</dd>
      
      <dt>Style languages &amp; frameworks</dt>
      <dd>CSS3, SCSS, Stylus, Bootstrap, Responsive design</dd>

      <dt>Databases</dt>
      <dd>PostgreSQL, SQL queries, MongoDB, built-in JSON API</dd>

      <!-- <dt>Methodologies</dt>
      <dd>Agile, TDD/BDD</dd>

      <dt>Management</dt>
      <dd>GitHub, Git Flow, Pivotal Tracker, Trello, Asana, Invision</dd> -->

      <dt>Design software</dt>
      <dd>Sketch, Photoshop, Illustrator, inDesign</dd>

    </dl>
  </div>
</section>